Arch1:
  input_dim: 1
  name: enet
  num_classes: 4
Arch2:
  input_dim: 1
  name: vgg16
  num_classes: 2
Data:
  labeled_data_ratio: 0.9
  seed: 1
  unlabeled_data_ratio: 0.1
DataLoader:
  labeled_batch_size: 2
  num_workers: 0
  shuffle: true
  unlabeled_batch_size: 4
  val_batch_size: 1
Dataset: acdc
Optim:
  lr: 0.0001
  name: RAdam
RegScheduler:
  begin_epoch: 5
  max_epoch: 50
  max_value: 0.001
Scheduler:
  T_max: 90
  name: CosineAnnealingLR
  warmup:
    multiplier: 300
    total_epoch: 10
Trainer:
  device: cpu
  max_epoch: 100
  num_batches: 200
  save_dir: tmp
seed: 123
