Arch1:
  name: enet
  input_dim: 1
  num_classes: 4

RegScheduler:
  begin_epoch: 10
  max_epoch: 20
  max_value: 0.1

Dataset: acdc

Data:
  unlabeled_data_ratio: 0.95
  labeled_data_ratio: 0.05
  seed: 1

DataLoader:
  labeled_batch_size: 4
  unlabeled_batch_size: 6
  val_batch_size: 1
  shuffle: True
  num_workers: 4

Trainer:
  device: cuda
  save_dir: tmp
  num_batches: 200
  max_epoch: 100


seed: 123