Arch1:
  name: enet
  input_dim: 1
  num_classes: 4

Arch2:
  name: vgg16
  input_dim: 1
  num_classes: 2

Optim:
  name: RAdam
  lr: 0.0001

Scheduler:
  name: CosineAnnealingLR
  T_max: 90
  warmup:
    multiplier: 300
    total_epoch: 10

RegScheduler:
  begin_epoch: 10
  max_epoch: 80
  max_value: 0.1

Dataset: acdc

Data:
  unlabeled_data_ratio: 0.1
  labeled_data_ratio: 0.9
  seed: 1

DataLoader:
  labeled_batch_size: 4
  unlabeled_batch_size: 6
  val_batch_size: 1
  shuffle: True
  num_workers: 0

Trainer:
  device: cuda
  save_dir: tmp
  num_batches: 200
  max_epoch: 100


seed: 123